-- ============================================================
-- iSOPE Online — Database Schema
-- ============================================================
-- Run this entire file in the Supabase SQL Editor to recreate
-- all tables and storage buckets from scratch in a new project.
--
-- Prerequisites:
--   - New Supabase project created
--   - All existing tables dropped (if any)
--
-- Table creation order matters due to foreign key dependencies:
--   users, orgs, requirements
--     → member, org_requirement_status, requirementcomments
--       → evaluation_templates
--         → evaluation_template_questions, org_evaluations
--           → org_evaluation_responses
-- ============================================================


-- ============================================================
-- STEP 1: Storage Buckets
-- These are required for file uploads.
--   orglogos        — stores org logo/avatar images
--   requirement-pdfs — stores PDF submissions from orgs
-- Both are public so files can be displayed via public URL.
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('orglogos', 'orglogos', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('requirement-pdfs', 'requirement-pdfs', true)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- STEP 2: Custom sequence for org_requirement_status
--         Generates zero-padded 6-digit text IDs (e.g. 000001)
-- ============================================================
CREATE SEQUENCE IF NOT EXISTS org_requirement_status_auto_id_seq;


-- ============================================================
-- TABLE: users
-- Stores all authenticated users (Google OAuth + credentials).
-- Email and Name come from Google. Username and PasswordHash
-- are set during Create Account flow. ResetToken/ResetExpires
-- are used for the Forgot Password flow.
-- ============================================================
CREATE TABLE users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Email"         text NOT NULL UNIQUE,
  "Name"          text NOT NULL,
  "Orgs"          text,
  "Role"          text,
  "LastLogged"    timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  "Username"      text,
  "PasswordHash"  text,
  "ResetToken"    text,
  "ResetExpires"  text
);


-- ============================================================
-- TABLE: orgs
-- Stores student organizations. username is the primary key
-- and is used as a URL slug (e.g. /dashboard/orgs/csso).
-- email links the org to its Google account for login.
-- adviseremail links the adviser's Google account.
-- ============================================================
CREATE TABLE orgs (
  username     text PRIMARY KEY,
  name         text,
  bio          text,
  adviser      text,
  accreditlvl  bigint,
  avatar       text,
  email        text UNIQUE,
  adviseremail text,
  active       boolean DEFAULT true
);


-- ============================================================
-- TABLE: requirements
-- Global list of requirements defined by OSAS.
-- Each requirement can be assigned to orgs via
-- org_requirement_status.
-- ============================================================
CREATE TABLE requirements (
  id             text PRIMARY KEY,
  section        text NOT NULL,
  title          text,
  active         boolean,
  instructions   text,
  submissiontype text
);


-- ============================================================
-- TABLE: member
-- Stores org members. Populated via Excel upload.
-- organizations FK links to orgs.username.
-- ============================================================
CREATE TABLE member (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name  text NOT NULL DEFAULT '',
  organizations text NOT NULL REFERENCES orgs(username),
  school_year   text
);


-- ============================================================
-- TABLE: org_requirement_status
-- Tracks the submission/grading/approval status of each
-- requirement for each org. Uses a custom zero-padded 6-digit
-- text ID generated by the sequence above.
-- ============================================================
CREATE TABLE org_requirement_status (
  id              text NOT NULL DEFAULT lpad((nextval('org_requirement_status_auto_id_seq'))::text, 6, '0') PRIMARY KEY,
  "orgUsername"   text REFERENCES orgs(username),
  "requirementId" text REFERENCES requirements(id),
  submitted       boolean,
  graded          boolean DEFAULT false,
  score           bigint,
  start           date,
  due             date,
  grade           bigint,
  year            bigint,
  active          boolean NOT NULL DEFAULT true,
  freeformans     text,
  approved        boolean DEFAULT false
);


-- ============================================================
-- TABLE: requirementcomments
-- Threaded comments on a requirement submission, visible to
-- both the org and OSAS.
-- ============================================================
CREATE TABLE requirementcomments (
  id              uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "orgUsername"   text NOT NULL,
  "requirementId" text,
  "authorRole"    text,
  content         text,
  "createdAt"     timestamp without time zone DEFAULT now(),
  "authorEmail"   text,
  "authorName"    text,
  deleted         boolean,
  "statusId"      text
);


-- ============================================================
-- TABLE: evaluation_templates
-- Reusable evaluation form templates created by OSAS.
-- Questions are stored separately in
-- evaluation_template_questions.
-- ============================================================
CREATE TABLE evaluation_templates (
  id           uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title        text NOT NULL DEFAULT 'Evaluation Template',
  instructions text NOT NULL DEFAULT 'Answer the form',
  active       boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);


-- ============================================================
-- TABLE: evaluation_template_questions
-- Individual questions belonging to an evaluation template.
-- type can be: input, dropdown, likert, checkbox
-- options is a JSONB array of choices (for dropdown/checkbox).
-- ============================================================
CREATE TABLE evaluation_template_questions (
  id           uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "templateId" uuid NOT NULL REFERENCES evaluation_templates(id),
  type         text NOT NULL,
  text         text NOT NULL,
  options      jsonb,
  scale        integer,
  sort_order   integer NOT NULL DEFAULT 0,
  active       boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now()
);


-- ============================================================
-- TABLE: org_evaluations
-- An evaluation instance: a template assigned to a specific
-- org for a specific school year.
-- ============================================================
CREATE TABLE org_evaluations (
  id            uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "orgUsername" text NOT NULL,
  "templateId"  uuid NOT NULL REFERENCES evaluation_templates(id),
  school_year   integer,
  active        boolean NOT NULL DEFAULT true,
  archived      boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  archived_at   timestamptz
);


-- ============================================================
-- TABLE: org_evaluation_responses
-- A member's response to an org evaluation. answers is a
-- JSONB object mapping question IDs to their answers.
-- ============================================================
CREATE TABLE org_evaluation_responses (
  id                uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  "orgEvaluationId" uuid NOT NULL REFERENCES org_evaluations(id),
  "orgUsername"     text NOT NULL,
  "memberId"        integer NOT NULL,
  "respondentEmail" text,
  answers           jsonb NOT NULL DEFAULT '{}',
  submitted         boolean NOT NULL DEFAULT false,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
